services:
  app:
    build: .
    runtime: nvidia
    shm_size: '2gb'
    volumes:
      - ./app:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - NVIDIA_VISIBLE_DEVICES=all
      - DISPLAY=host.docker.internal:0.0 
    devices:
        - "/dev/video0:/dev/video0"
        - "/dev/video2:/dev/video2"
    privileged: true
    group_add:
      - video 
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: ["python", "__main__.py"]