FROM pytorch/pytorch:2.2.0-cuda11.8-cudnn8-runtime

RUN pip install --upgrade pip

WORKDIR /train_model

COPY train_model .
COPY requirements.txt .

RUN pip install -r requirements.txt

CMD ["python", "train.py"]
# CMD ["python", "__main__.py"]