version: "3.8"
services:
  app:
    build: .
    runtime: nvidia
    shm_size: '2gb'
    privileged: true
    group_add:
      - video

    # Dispositivos de cámara
    devices:
      - "/dev/video0:/dev/video0"
      - "/dev/video2:/dev/video2"

    # Mapea Flask 5000 → host:8000 (puedes cambiar host_port)
    ports:
      - "8000:5000"

    # GPU y variables de entorno
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - DISPLAY=${DISPLAY}
      - SELECTED_MODE=${SELECTED_MODE:-inference}
    volumes:
      - ./train_model:/train_model
      - /tmp/.X11-unix:/tmp/.X11-unix

    entrypoint: ["/entrypoint.sh"]
    command: ["inference"]
