version: '3.8'

services:
  app:
    build: .
    runtime: nvidia
    shm_size: '2gb'
    volumes:
      - ./train_model/__main__.py:/train_model/__main__.py 
      # - ./recycling_detection:/recycling_detection
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - NVIDIA_VISIBLE_DEVICES=all
    command: ["python", "__main__.py"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]