services:
  app:
    build: .
    runtime: nvidia
    shm_size: '2gb'
    privileged: true

    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - DISPLAY=${DISPLAY}
      - SELECTED_MODE=${SELECTED_MODE:-inference}

    volumes:
      - ./train_model:/train_model
      - /tmp/.X11-unix:/tmp/.X11-unix

    entrypoint: ["/entrypoint.sh"]
    command: ["inference"]